version: '3'
services:
    example:
        container_name: example
        image: nginx
        # if need build customized image
        # image: test
        # build:
        #     context: .
        ports:
            - "9080:80"
            - "9081:80"
        volumes:
            - ./data:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf